### ISSUE TITLE
Error when rendering

### ISSUE THREAD

**Issue by drfurtado** [jmbuhr/quarto-qrcode#2]
I am getting the following error when rendering a document. Any ideas why? Thank you.

> quarto install extension jmbuhr/quarto-qrcode
Error: unexpected symbol in "quarto install"

**Comment by drfurtado** [comment]
I am sorry, the error was unrelated to the extension.
BTW, great extension....

**Comment by jmbuhr** [comment]
No worries. Sounds like the quarto docs could be clearer about quarto being executed on the command line, not the R console.
