### ISSUE TITLE
Problems with reveal slides and more than one qrcode!

### ISSUE THREAD

**Issue by NMarkgraf** [jmbuhr/quarto-qrcode#3]
Hello,

I ran into a problem, when I tried to use qrcode more than one qrcode on different pages in a qmd-file rendered to revealJS. All qrcodes will be on the page of the first qrcode in a row. On the page later, where I want the 2nd qrcode, nothing will be shown.

Yours
Norman

**Comment by jmbuhr** [comment]
Thanks for the report. I'm assuming this is happening even with giving ids to the qrcodes as shown in https://jmbuhr.de/quarto-qrcode/?

**Comment by jmbuhr** [comment]
I can not reproduce this with:
````
---
title: Hello
format:
 revealjs: default
---

## Slide 1

{{< qrcode https://jmbuhr.de q1 >}}

## Slide 2

{{< qrcode https://jmbuhr.de q2 >}}

````

feel free to re-open this issue with a counterexample.

**Comment by NMarkgraf** [comment]
And here it is:

```
---
title: Hello
format:
 revealjs: default
---

## Slide 1

{{< qrcode https://jmbuhr.de >}}

## Slide 2

{{< qrcode https://sefiroth.de >}}

```

**Comment by jmbuhr** [comment]
Just ad a unique id to each qr code and you are good to go. See

> "Supply an ID as the second argument (here qr1 and qr2) if you have more than one qrcode to keep them separate." (https://jmbuhr.de/quarto-qrcode/).

If this is unclear I am happy about suggestions for rephrasing the documentation.

**Comment by NMarkgraf** [comment]
Well, a RTFM kind of bug. ;-) -- Danke!
