### ISSUE TITLE
Minimal example?

### ISSUE THREAD

**Issue by sammo3182** [jmbuhr/quarto-qrcode#4]
Dear Jannik @jmbuhr,

The extension looks very fun, however, I can't make it work on my quarto slides. Do you mind providing a minimal **qmd** example to illustrate how to use it? Should I add `- qrcode` to either `filter` or `extension` in the YAML? (Neither works on my side, btw) 

Thanks!

**Comment by jmbuhr** [comment]
If https://github.com/jmbuhr/quarto-qrcode#installing and the example (index.qmd) is not working I'd be happily review your example in which it doesn't work.
