### ISSUE TITLE
what is the purpose ??

### ISSUE THREAD

**Issue by JOduMonT** [jmbuhr/quarto-qrcode#5]
Hi; thanks for your work
but what is the purpose?
Does it generate a QRCode for every article by itself, or it's just a QR-Code for the whole project
or it just generates an image, then I have to add my URL by myself.
Because if it's the last case, I just have to go [here](https://davidshimjs.github.io/qrcodejs/) then copy and paste the image into my project, which would same a lot of code and maintenance and resources.

**Comment by jmbuhr** [comment]
You might want to start with the readme.
