### ISSUE TITLE
Center QR code in reveal

### ISSUE THREAD

**Issue by brambozz** [jmbuhr/quarto-qrcode#8]
Hey there!

Thanks for the extension, very nice! I had some trouble using this inside the reveal format. I can add it fine, but I would like to be able horizontally center the QR code.

For text I can do e.g.

```
::: {style="text-align: center;}
This text is centered
:::
```

But having the QR shortcode inside that does not help. Any ideas on how to get it horizontally centered?

**Comment by jmbuhr** [comment]
I usually assign an id to the qrcode (see https://jmbuhr.de/quarto-qrcode/) and use css to position it. e.g.

```css
#qr1 {
  position: absolute;
  top: 0;
  right: 50%;
}
```

**Comment by brambozz** [comment]
Thanks, that works!
